name: Compile .txt to .srs

on:
  push:
    paths:
      - '**/*.txt'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # 获取至少两个提交的历史记录

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Download sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.9.0/sing-box-1.9.0-linux-amd64v3.tar.gz
        tar -xzf sing-box-1.9.0-linux-amd64v3.tar.gz
        mv sing-box-1.9.0-linux-amd64v3/sing-box ./sing-box
        chmod +x ./sing-box

    - name: Run compile.py for changed .txt files
      run: |
        changed_files=$(git diff --name-only HEAD~1 HEAD -- '*.txt' || git diff --name-only HEAD -- '*.txt')
        for file in $changed_files; do
          python compile.py "$file"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.srs
        git commit -m 'Add compiled .srs files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
