name: Compile .txt to .srs

on:
  push:
    paths:
      - '**/*.txt'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Download sing-box
      run: |
        LATEST_URL=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep "browser_download_url" | grep "linux-amd64.tar.gz" | cut -d '"' -f 4)
        wget "$LATEST_URL" -O sing-box-latest-linux-amd64.tar.gz
        tar -xzf sing-box-latest-linux-amd64.tar.gz
        mv sing-box*/sing-box ./sing-box
        chmod +x ./sing-box

    - name: Clone and process dnsmasq-china-list
      run: |
        git clone --depth=1 https://github.com/felixonmars/dnsmasq-china-list.git dnsmasq-list
        sed -e 's|^server=/\(.*\)/114.114.114.114$$|\1|' dnsmasq-list/accelerated-domains.china.conf | grep -Ev -e '^#' -e '^$$' > accelerated-domains.china.txt
        sed -e 's|^server=/\(.*\)/114.114.114.114$$|\1|' dnsmasq-list/google.china.conf | grep -Ev -e '^#' -e '^$$' > google.china.txt
        sed -e 's|^server=/\(.*\)/114.114.114.114$$|\1|' dnsmasq-list/apple.china.conf | grep -Ev -e '^#' -e '^$$' > apple.china.txt
        
    - name: Download anti-AD list
      run: wget -O anti_ad_domains.txt https://anti-ad.net/domains.txt

    - name: Run compile.py for all .txt files
      run: |
        for file in *.txt; do
            python compile.py "$file"
        done
      
    - name: Create Release
      run: |
        # Fixed tag name
        TAG=$(date +'%Y%m%d')
        
        # Create release
        gh release create $TAG \
          --title "$TAG" \
          --notes "Automatically generated rule sets" \
          *.srs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}